### ISSUE TITLE
320 kb/s, 320 khz, 320 quality... 🤡

### ISSUE THREAD

**Issue by g1nt0** [PS2ClassicsVault/Audio-HD-Enhancer-Magisk-Module#1]
![IMG_20241126_230648_164](https://github.com/user-attachments/assets/29e956e0-4616-4d9c-b58b-2000b8ed6248)

stop it, pls.

**Comment by citizenserious** [comment]
### Unrealistic Audio Configuration in "Audio-HD-Enhancer-Magisk-Module"

The values in the **"Audio-HD-Enhancer-Magisk-Module"** configuration seem more like marketing than technically sensible settings. Here's a detailed explanation:

---

### **1. What Does the Module Do?**
The **"Audio-HD-Enhancer-Magisk-Module"** is likely designed to "optimize" or "enhance" audio output on Android devices by modifying system settings such as sampling rates and resampling quality.

The listed values aim to:
- Suggest higher audio quality.
- Process audio data with extreme precision (in theory).

---

### **2. Why These Values Are Unrealistic**
#### **Sampling Rates of 320000 Hz**
- **Hardware Limitations**: Most audio chips in smartphones support a maximum of **192000 Hz** (Hi-Res Audio). Even high-end devices rarely utilize this fully.
- **Human Perception**: Frequencies above 192000 Hz are inaudible since human hearing is limited to around 20 kHz (20000 Hz). These values provide no practical benefit.

#### **Resampling Quality**
- Values like `af.resampler.quality=320` are exaggerated. Typically, a quality setting of `90` or `100` is sufficient and avoids unnecessary strain on system resources.

#### **Technical Inefficiency**
- Enforcing extreme values in system settings can lead to:
  1. **Performance Issues**: Higher CPU usage and battery drain.
  2. **Errors or Incompatibility**: Hardware or software may not support these values, leading to system instability.

---

### **3. Potential Benefits of the Module**
- Some modules genuinely improve audio processing, for instance, by providing better drivers or high-quality resampling algorithms.
- However, if a module simply forces excessive values, it is more likely to degrade performance than to enhance the user experience.

---

### **4. Conclusion**
- **Is It Useful?** In its current state: No. These values exceed realistic limits and could strain the system without providing any noticeable improvement.
- **Recommendation**: Test the module to see if it delivers any **noticeable audio quality improvement**. If it doesn't, consider uninstalling it. Alternatives like **Viper4Android** are proven to enhance audio quality without relying on unrealistic configurations.

**Comment by g7755726** [comment]
I decided to relook into this issue and reworking the modules 

And also viper doesn't work withnewer devices made in 2024 due to new libaries

**Comment by g1nt0** [comment]
https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings/blob/master/system.prop

here you can take the values for "quality" sound

**Comment by g7755726** [comment]
> https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings/blob/master/system.prop
> 
> here you can take the values for "quality" sound

Thanks I'll take a look

**Comment by g7755726** [comment]
> https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings/blob/master/system.prop
> 
> here you can take the values for "quality" sound

Okay the sound is a bit more comfortable previously it was too loud and it gave me a headache sometimes and I noticed a big performance improvement since reworking it. Is this seem more suitable?

`ro.audio.samplerate=192000
ro.audio.pcm.samplerate=19200
persist.audio.pcm.channels=2
af.resample=96000
af.resampler.quality=100`

**Comment by g7755726** [comment]
> https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings/blob/master/system.prop
> 
> here you can take the values for "quality" sound

The update is.live.sorry for the notification

**Comment by g1nt0** [comment]
> > https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings/blob/master/system.prop
> > here you can take the values for "quality" sound
> 
> Okay the sound is a bit more comfortable previously it was too loud and it gave me a headache sometimes and I noticed a big performance improvement since reworking it. Is this seem more suitable?
> 
> `ro.audio.samplerate=192000 ro.audio.pcm.samplerate=19200 persist.audio.pcm.channels=2 af.resample=96000 af.resampler.quality=100`


I use these settings:

```
ro.config.media_vol_steps=25
audio.safemedia.bypass=true
audio.safemedia.force=false
audio.safemedia.csd.force=false
ro.audio.ignore_effects=true
ro.audio.spatializer_enabled=false
ro.vendor.audio.dolby.dax.support=false
vendor.audio.dolby.control.support=false
vendor.audio.usb.perio=2000
vendor.audio.usb.out.period_us=2000
vendor.audio.usb.out.period_count=2
vendor.audio_hal.period_size=120
vendor.audio_hal.period_multiplier=1
vendor.audio.adm.buffering.ms=2
persist.bluetooth.sbc_hd_higher_bitrate=1
af.resampler.quality=7
ro.audio.resampler.psd.enable_at_samplerate=44100
ro.audio.resampler.psd.stopband=194
ro.audio.resampler.psd.halflength=520
ro.audio.resampler.psd.cutoff_percent=100

```
